"""Render RECORDING-SCRIPT.md and the TESTS.md scenario body from scenarios.yaml.

DRY, per CLAUDE.md: the scenario corpus has exactly one source of truth. The
recording script a human reads from and the scenario tables in docs/TESTS.md are
both *derived*, never hand-edited. Editing them directly is a defect - the next
run of this script silently reverts it.

Usage:
    python scripts/render_docs.py            # write both files
    python scripts/render_docs.py --check    # exit 1 if either is stale

`--check` is what CI runs, so a scenarios.yaml edit that forgets to re-render is
caught at review time rather than discovered when a reader records the wrong line.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

AGENT_ROOT = Path(__file__).resolve().parent.parent
REPO_ROOT = AGENT_ROOT.parent
SCENARIOS = AGENT_ROOT / "tests" / "audio" / "scenarios.yaml"
RECORDING_SCRIPT = AGENT_ROOT / "tests" / "audio" / "RECORDING-SCRIPT.md"
TESTS_DOC = REPO_ROOT / "docs" / "TESTS.md"

GENERATED_BANNER = (
    "<!-- GENERATED BY agent/scripts/render_docs.py FROM "
    "agent/tests/audio/scenarios.yaml. DO NOT EDIT BY HAND. -->"
)


def load() -> dict[str, Any]:
    with SCENARIOS.open(encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def flow(text: str | None) -> str:
    """Collapse a YAML folded block into one line."""
    return " ".join((text or "").split())


def wav_path(scenario_id: str, turn: int) -> str:
    return f"raw/{scenario_id}/t{turn:02d}.wav"


# --------------------------------------------------------------- recording script


def render_recording_script(doc: dict[str, Any]) -> str:
    scenarios = doc["scenarios"]
    total_turns = sum(len(s["turns"]) for s in scenarios)

    out: list[str] = [
        GENERATED_BANNER,
        "",
        "# Recording script — emergency voice test corpus",
        "",
        f"**{len(scenarios)} scenarios · {total_turns} lines to record.**",
        "",
        "You are recording the **responder** only — the person phoning for help.",
        "The agent's replies are never recorded; they live in `docs/TESTS.md` as text.",
        "",
        "---",
        "",
        "## Before you start",
        "",
        "**Recording settings**",
        "",
        "| Setting | Value |",
        "|---|---|",
        "| Format | WAV, 16-bit PCM |",
        "| Sample rate | 48000 Hz (44100 also fine) |",
        "| Channels | Mono |",
        "| Room | Quiet. Ambient noise is added later — do not add your own |",
        "",
        "**Where files go.** One folder per scenario, one file per line, "
        "under `agent/tests/audio/`:",
        "",
        "```",
        "agent/tests/audio/raw/<scenario_id>/t01.wav",
        "                                   /t02.wav",
        "```",
        "",
        "The filename is the contract. `build_corpus.py` finds lines by this path "
        "and reports any that are missing rather than failing — so you can record "
        "in any order, and record a few scenarios now and the rest later.",
        "",
        "**How to perform these.** Read the *direction* line before each take. "
        "It carries the delivery: pace, breathing, volume, emotional state. The "
        "words alone are not the test — a panicked line read calmly tests nothing "
        "that matters.",
        "",
        "Specifically:",
        "",
        "- **Do not enunciate.** Real callers slur, trail off, and talk over "
        "themselves. Clean diction is the wrong sound.",
        "- **Breathe audibly** where the direction says you are out of breath. "
        "That breath is signal, not noise.",
        "- **Let sentences collapse.** Where a line ends in `—`, run out of words "
        "rather than finishing neatly.",
        "- **Keep one take per line.** Do not splice.",
        "- A `—` mid-line is a self-interruption: stop dead and restart the "
        "thought. This is deliberate and is being tested (see F-001).",
        "",
        "**You do not need to change your voice.** The mix stage shifts pitch and "
        "formants per scenario (±2 semitones, formant-preserving) so one reader "
        "becomes twelve distinguishable callers. Read in your own voice.",
        "",
        "---",
        "",
        "## Progress checklist",
        "",
        "| Scenario | Lines | Scene | Done |",
        "|---|---|---|---|",
    ]

    for scenario in scenarios:
        out.append(
            f"| `{scenario['id']}` | {len(scenario['turns'])} "
            f"| {flow(scenario['scene']['place'])} | ☐ |"
        )

    out += ["", "---", ""]

    for scenario in scenarios:
        scene = scenario["scene"]
        voice = scenario["voice"]
        out += [
            f"## {scenario['id']}",
            "",
            f"### {scenario['title']}",
            "",
            f"**Scene.** {flow(scene['place'])} — {flow(scene['description'])}",
            "",
            f"**Peak criticality:** {scenario['criticality_peak']} · "
            f"**Lines:** {len(scenario['turns'])} · "
            f"**Voice treatment:** {voice['semitones']:+g} semitones, "
            f"rate {voice['rate']}, `{voice['channel']}`",
            "",
        ]

        for turn in scenario["turns"]:
            out += [
                f"#### Line {turn['n']} — `{wav_path(scenario['id'], turn['n'])}`",
                "",
                f"> {flow(turn['text'])}",
                "",
                f"*{flow(turn['direction'])}*",
                "",
            ]

        out += ["---", ""]

    return "\n".join(out).rstrip() + "\n"


# ------------------------------------------------------------------ tests doc


LEVEL_NAMES = {1: "Minor", 2: "Low", 3: "Moderate", 4: "Severe", 5: "Critical"}


def render_scenario_sections(doc: dict[str, Any]) -> str:
    """The per-scenario body of docs/TESTS.md."""
    out: list[str] = []

    for scenario in doc["scenarios"]:
        scene = scenario["scene"]
        voice = scenario["voice"]
        peak = scenario["criticality_peak"]
        snr = scene["snr_db"]
        snr_note = (
            f"{snr} dB → {scene['snr_db_end']} dB"
            if "snr_db_end" in scene
            else f"{snr} dB"
        )

        out += [
            f"### {scenario['id']} — {scenario['title']}",
            "",
            f"**Peak criticality {peak} ({LEVEL_NAMES[peak]})**",
            "",
            flow(scenario["summary"]),
            "",
            "| | |",
            "|---|---|",
            f"| **Scene** | {flow(scene['place'])} |",
            f"| **Ambient** | {flow(scene['description'])} |",
            f"| **Bed / SNR** | `{scene['bed']}` at {snr_note} |",
            f"| **Voice** | {voice['semitones']:+g} st, rate {voice['rate']}, "
            f"`{voice['channel']}` |",
            "",
            "#### Dialogue and expected outcomes",
            "",
        ]

        for turn in scenario["turns"]:
            triage = turn["triage"]
            fired = turn.get("expect_markers") or []
            forbidden = turn.get("expect_no_markers") or []
            defect = turn.get("defect")

            out += [
                f"**R{turn['n']} — responder**",
                "",
                f"> {flow(turn['text'])}",
                "",
                f"*Delivery: {flow(turn['direction'])}*",
                "",
            ]

            rows = [
                "| Layer | Expected |",
                "|---|---|",
                "| **Markers fired** | "
                + (", ".join(f"`{m}`" for m in fired) if fired else "*none*")
                + " |",
            ]
            if forbidden:
                rows.append(
                    "| **Must NOT fire** | "
                    + ", ".join(f"`{m}`" for m in forbidden)
                    + " |"
                )
            rows.append(
                f"| **Criticality** | {triage['level']} "
                f"({LEVEL_NAMES[triage['level']]}) |"
            )
            rows.append(f"| **Escalation** | `{triage['escalation']}` |")
            if triage.get("downgrade_refused"):
                rows.append("| **Ratchet** | downgrade refused |")

            agent = turn.get("agent") or {}
            if agent.get("tools"):
                rows.append(
                    "| **Agent should call** | "
                    + ", ".join(f"`{t}`" for t in agent["tools"])
                    + " |"
                )
            if agent.get("protocols"):
                rows.append(
                    "| **Protocols retrieved** | "
                    + ", ".join(f"`{p}`" for p in agent["protocols"])
                    + " |"
                )
            if defect:
                rows.append(f"| **⚠ Known defect** | {defect} |")

            out += rows + [""]

            if triage.get("note"):
                note = flow(triage["note"]).replace(" . ", "\n>\n> ")
                prefix = "> **⚠ " + defect + "** — " if defect else "> **Why.** "
                out += [prefix + note, ""]

        out += ["---", ""]

    return "\n".join(out)


def render_tests_doc(doc: dict[str, Any]) -> str:
    scenarios = doc["scenarios"]
    total_turns = sum(len(s["turns"]) for s in scenarios)
    defect_turns = [
        (s["id"], t["n"], t["defect"])
        for s in scenarios
        for t in s["turns"]
        if t.get("defect")
    ]

    by_level: dict[int, list[str]] = {}
    for scenario in scenarios:
        by_level.setdefault(scenario["criticality_peak"], []).append(scenario["id"])

    header = [
        GENERATED_BANNER,
        "",
        "# Voice triage test scenarios",
        "",
        f"**{len(scenarios)} scenarios · {total_turns} responder turns · "
        f"{len(defect_turns)} turns exercising a known defect.**",
        "",
        "This document is the human-readable face of "
        "`agent/tests/audio/scenarios.yaml`, which is the machine-readable "
        "source of truth. Both are rendered by "
        "`agent/scripts/render_docs.py`; neither is edited by hand.",
        "",
        "---",
        "",
        "## What these scenarios test",
        "",
        "Every responder turn carries expectations for three layers that fail "
        "independently:",
        "",
        "| Layer | Module | Deterministic? | Asserted where |",
        "|---|---|---|---|",
        "| **Markers** | `phrases.py` | Yes — pure function of text | "
        "Default hermetic suite |",
        "| **Triage** | `triage.py` | Yes — criticality, ratchet, escalation | "
        "Default hermetic suite |",
        "| **Agent** | `agent.py` + LLM | No — model-dependent | "
        "`infra`-marked suite |",
        "",
        "The `Must NOT fire` rows are the strongest assertions in the corpus. "
        "Proving a marker fires shows the net catches something; proving it "
        "*stays silent* on a negated phrase is what stops the system crying "
        "wolf — and a safety net that escalates every fainting passenger will "
        "be ignored when a real arrest arrives.",
        "",
        "## Coverage by criticality",
        "",
        "| Level | Scenarios |",
        "|---|---|",
    ]

    for level in sorted(by_level):
        ids = ", ".join(f"`{i}`" for i in by_level[level])
        header.append(f"| **{level} — {LEVEL_NAMES[level]}** | {ids} |")

    header += [
        "",
        "## How the audio is produced",
        "",
        "```",
        "RECORDING-SCRIPT.md  →  a human reads the lines  →  raw/<scenario>/tNN.wav",
        "                                                          │",
        "   beds/ (Freesound CC0, fetched once)  ──────────────────┤",
        "                                                          │",
        "                          build_corpus.py  (offline, deterministic)",
        "                          · formant-preserving pitch shift, ±2 st",
        "                          · time-stretch for pace",
        "                          · ambient bed mixed at the scenario's SNR",
        "                          · phone-channel simulation",
        "                                                          │",
        "                                              mixed/<scenario>/tNN.wav",
        "                                                          │",
        "                          Deepgram nova-3-medical  (--transcribe, network)",
        "                                                          │",
        "                                                  manifest.json",
        "                                                          │",
        "                          pytest  (hermetic — reads manifest.json only)",
        "```",
        "",
        "The oracle is **the transcript Deepgram actually produced**, not the "
        "text the reader was given. That distinction is the point: if the STT "
        "returns a curly apostrophe in `isn't breathing`, or ambient noise "
        "corrupts a safety-critical phrase, the manifest records it and the "
        "assertions run against reality rather than against intent.",
        "",
        "---",
        "",
    ]

    return "\n".join(header) + "\n" + render_scenario_sections(doc)


# ------------------------------------------------------------------------ main


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the rendered files are current; write nothing",
    )
    args = parser.parse_args()

    doc = load()
    targets = {
        RECORDING_SCRIPT: render_recording_script(doc),
        TESTS_DOC: render_tests_doc(doc),
    }

    if args.check:
        stale = [
            path
            for path, content in targets.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            for path in stale:
                print(f"STALE: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
            print(
                "\nRun: python agent/scripts/render_docs.py",
                file=sys.stderr,
            )
            return 1
        print(f"up to date: {len(targets)} file(s)")
        return 0

    for path, content in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)} ({len(content):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
